name: Rust

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build --release --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: espadrille
        path: target/release/espadrille
